name: main
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  stack: ^0.2.1

dependencies:
  intl: ^0.17.0
  supabase: ^1.2.0
  coverage: ^1.6.0
